import { bench } from "@ark/attest";
import { z } from "zod";
import { zodSchema } from "../fixtures/schema.ts";
import type { ContractDef } from "../../src/contract/types.js";

undefined as undefined;

import type { Client } from "../../src/client/types.js";

bench("combined-40", () => {
  const contract = {
    getRoute0: {
      method: "GET" as const,
      path: "/items/0",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute1: {
      method: "GET" as const,
      path: "/items/1",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute2: {
      method: "GET" as const,
      path: "/items/2",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute3: {
      method: "GET" as const,
      path: "/items/3",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute4: {
      method: "GET" as const,
      path: "/items/4",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute5: {
      method: "GET" as const,
      path: "/items/5",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute6: {
      method: "GET" as const,
      path: "/items/6",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute7: {
      method: "GET" as const,
      path: "/items/7",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute8: {
      method: "GET" as const,
      path: "/items/8",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute9: {
      method: "GET" as const,
      path: "/items/9",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute10: {
      method: "GET" as const,
      path: "/items/10",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute11: {
      method: "GET" as const,
      path: "/items/11",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute12: {
      method: "GET" as const,
      path: "/items/12",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute13: {
      method: "GET" as const,
      path: "/items/13",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute14: {
      method: "GET" as const,
      path: "/items/14",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute15: {
      method: "GET" as const,
      path: "/items/15",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute16: {
      method: "GET" as const,
      path: "/items/16",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute17: {
      method: "GET" as const,
      path: "/items/17",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute18: {
      method: "GET" as const,
      path: "/items/18",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute19: {
      method: "GET" as const,
      path: "/items/19",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute20: {
      method: "GET" as const,
      path: "/items/20",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute21: {
      method: "GET" as const,
      path: "/items/21",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute22: {
      method: "GET" as const,
      path: "/items/22",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute23: {
      method: "GET" as const,
      path: "/items/23",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute24: {
      method: "GET" as const,
      path: "/items/24",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute25: {
      method: "GET" as const,
      path: "/items/25",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute26: {
      method: "GET" as const,
      path: "/items/26",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute27: {
      method: "GET" as const,
      path: "/items/27",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute28: {
      method: "GET" as const,
      path: "/items/28",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute29: {
      method: "GET" as const,
      path: "/items/29",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute30: {
      method: "GET" as const,
      path: "/items/30",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute31: {
      method: "GET" as const,
      path: "/items/31",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute32: {
      method: "GET" as const,
      path: "/items/32",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute33: {
      method: "GET" as const,
      path: "/items/33",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute34: {
      method: "GET" as const,
      path: "/items/34",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute35: {
      method: "GET" as const,
      path: "/items/35",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute36: {
      method: "GET" as const,
      path: "/items/36",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute37: {
      method: "GET" as const,
      path: "/items/37",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute38: {
      method: "GET" as const,
      path: "/items/38",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
    getRoute39: {
      method: "GET" as const,
      path: "/items/39",
      query: zodSchema(z.object({ id: z.string() })),
      output: zodSchema(z.object({ id: z.string(), value: z.number() })),
      errors: { not_found: 404, forbidden: 403 } as const,
    },
  } satisfies ContractDef;
  return {} as Client<typeof contract>;
}).types([98341, "instantiations"]);
